import {Inter, JetBrains_Mono} from "next/font/google";
import MainHeader from "@/components/main-header/main-header";
import './globals.css'
import Footer from "@/components/main/footer";

const inter = Inter({ subsets: ["latin"] });
const jetbrainsMono = JetBrains_Mono({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </head>
      <body className={jetbrainsMono.className + " "}>
            {children}
        <Footer />
      </body>
    </html>
  );
}
